title: "Omar Masri Personal Website"
description: "A portfolio showcasing my work in technology and cybersecurity."
theme: minima

# Color Scheme
colors:
  primary: '#000000'  # Black
  secondary: '#ffffff'  # White background
  background: '#ffffff'  # White background for the page
  text: '#000000'  # Black text
  link: '#000000'  # Black links

# Enable light theme styling for the site
light_mode: true

# Optional: Social links and other configurations can go here
social_links:
  tiktok: "https://www.tiktok.com/@omar.masri03"
  linkedin: "https://www.linkedin.com/in/omar-masri-32556932b/"
  github: "https://github.com/Coollomar1"

markdown: kramdown
