title: "Omar Masri Personal Website"
description: "A portfolio showcasing my work in technology and cybersecurity."
theme: minima

# Color Scheme
colors:
  primary: '#9b4dca'  # Purple
  secondary: '#6a1e9c'  # Darker Purple
  background: '#ffffff'  # White background
  text: '#121212'  # Dark text for contrast
  link: '#9b4dca'  # Purple accent for links

# Enable light theme styling for the site
light_mode: true

# Optional: Social links and other configurations can go here
social_links:
  tiktok: "https://www.tiktok.com/@omar.masri03"
  linkedin: "https://www.linkedin.com/in/omar-masri-32556932b/"
  github: "https://github.com/Coollomar1"

markdown: kramdown
