title: "Omar Masri Personal Website"
description: "A portfolio showcasing my work in technology and cybersecurity."
theme: minima

colors:
  primary: '#0099FF'  # Blue
  secondary: '#0059B3'  # Darker Blue
  background: '#FFFFFF'  # White background
  text: '#121212'  # Dark text for readability
  link: '#0066CC'  # Accent color for links

# Optional: Social links and other configurations can go here
social_links:
  tiktok: "https://www.tiktok.com/@omar.masri03"
  linkedin: "https://www.linkedin.com/in/omar-masri-32556932b/"
  github: "https://github.com/Coollomar1"

markdown: kramdown
highlighter: rouge
