# _config.yml

title: "Omar Masri Personal Website"
theme: jekyll-theme-slate
parallax: true  # Enable parallax scrolling effect

colors:
  primary: '#9b4dca'  # Purple
  secondary: '#6a1e9c'  # Darker Purple
